### ISSUE TITLE
Visitor stats viewer not working 

### ISSUE THREAD

**Issue by SH20RAJ** [estruyf/web-visitorbadge-nextjs#10]

**Comment by estruyf** [comment]
Could you share the URL you try to access?

**Comment by SH20RAJ** [comment]
> Could you share the URL you try to access?
https://visitorbadge.io/status?path=DevArt

**Comment by estruyf** [comment]
The issue has been fixed; you should be able to view your stats again.

**Comment by SH20RAJ** [comment]
> The issue has been fixed; you should be able to view your stats again.

I can see many more new features also added how did you do this

**Comment by estruyf** [comment]
It has always been like that, but a couple of weeks ago, I upgraded the backend to the latest version and noticed that some queue messages needed to be correctly created for paths like yours. I fixed it yesterday so you will see more information on the status page.

It works based on the limited data that the endpoint gets from calling the image some basic HTTP / browser logic.

**Comment by SH20RAJ** [comment]
Oooh ok, One more thing can you add no. of unique visitors also, because users refreshes the page and new videos are created I got 10k+ views but when I checked my another analytics tool (i.e iplogger, grabify) founded that there are less than 10 views all other was bot views may be because Google was crawling my website that time.

- Unique Visitor Count 
- Bot identifiers 

![Screenshot_20240405_143636](https://github.com/estruyf/web-visitorbadge-nextjs/assets/66713844/55c2864a-e8aa-4f6f-9dd6-69d3e711d77d)
![Screenshot_20240405_143640](https://github.com/estruyf/web-visitorbadge-nextjs/assets/66713844/81f3bfc7-d8b3-4b94-9b77-194857c1e251)
![Screenshot_20240405_143644](https://github.com/estruyf/web-visitorbadge-nextjs/assets/66713844/95696122-d9ed-4a4b-b87a-7373b7259a14)

**Comment by estruyf** [comment]
Currently, there are no plans to add unique visitors to the service. It is a "simple" visitor badge. A WAF rule on Cloudflare blocks most bots and scrapers.

**Comment by estruyf** [comment]
BTW, I've added `Bytespider` to the list.

**Comment by estruyf** [comment]
![image](https://github.com/estruyf/web-visitorbadge-nextjs/assets/2900833/1dcf60b1-a6f0-420f-9608-bf209b26e091)

**Comment by SH20RAJ** [comment]
And all set

**Comment by SH20RAJ** [comment]
Is there any api to get the details in the form of JSON

**Comment by estruyf** [comment]
@SH20RAJ, there is one, but it is only available on the status page and provides 2 days of stats (or 7 days if you support the project). I've considered giving another option from 7 -> 14 -> 30 days of stats. In addition, I could open the API for people who support the project. The reasoning behind it is to cover the cost of the services.

**Comment by SH20RAJ** [comment]
Ok
