### ISSUE TITLE
Website isn't working or sometimes very slow

### ISSUE THREAD

**Issue by SH20RAJ** [estruyf/web-visitorbadge-nextjs#11]

**Comment by estruyf** [comment]
@SH20RAJ is this still the case?

**Comment by SH20RAJ** [comment]
> @SH20RAJ is this still the case?

Loading but very slow

**Comment by estruyf** [comment]
Would you be able to show me network traffic from the website? Screenshot from the browser developer tools its network tab is fine.

**Comment by SH20RAJ** [comment]
<img width="1470" alt="Screenshot 2024-07-03 at 11 17 26 PM" src="https://github.com/estruyf/web-visitorbadge-nextjs/assets/66713844/8a1173fd-0f11-46d5-ab57-9b1220096d24">

See the time here

**Comment by estruyf** [comment]
Thanks! So, it is not the website itself but creating a new badge. For new badges, there is some extra logic on the backend. Someone else reported it a couple of days ago. I will look at what can be optimized to lower the response times.

For a couple of weeks, tests have been running to verify the API's performance in 10 different locations worldwide.

**Comment by estruyf** [comment]
@SH20RAJ I have made some changes on the backend, and the performance for new badges should now be much better.
