### ISSUE TITLE
Disable counter incrementation using a specific parameter

### ISSUE THREAD

**Issue by tarampampam** [estruyf/web-visitorbadge-nextjs#12]
Hi there!

I might have missed this in the documentation, but does the API support a special "get" parameter to prevent the counter from incrementing? My use case is as follows:

- The counter badge is included on the pages where I want to track visit counts (e.g., blog posts).
- In another place (e.g., blog sidebar), I want to display badges with the post read count to show how often each post has been read.

In this case, I want to prevent the counter from incrementing during the sidebar rendering to avoid false counter changes. Could you explain if this is possible?

Thank you!

**Comment by estruyf** [comment]
There is an undocumented property `&readonly=true` which you can use.

**Comment by tarampampam** [comment]
U're awesome, thank you!

**Comment by tarampampam** [comment]
As a side note, the API of `visitorbadge` is unfortunately too slow:

```
$ time curl 'https://api.visitorbadge.io/api/visitors?path=test2&label=TEMPLATE_NAME&countColor=%23007ec6'
...
real	0m6.495s
user	0m0.051s
sys	0m0.009s

$ time curl 'https://api.visitorbadge.io/api/visitors?path=test2&label=TEMPLATE_NAME&countColor=%23007ec6&readonly=true'
...
real	0m6.359s
user	0m0.047s
sys	0m0.013s
```

The median response time is 6 seconds to render a simple badge, which is too long for most cases 😞

**Comment by estruyf** [comment]
This might concern the geolocation and where the service is running. Expanding the services to multiple regions is not yet something I'm considering due to the cost.

**Comment by tarampampam** [comment]
I understand, and I wish you the best of luck. And I hope you receive enough donations to improve it soon! 🤝

**Comment by estruyf** [comment]
Can you show me the network request information from your browser?

**Comment by tarampampam** [comment]
![image](https://github.com/estruyf/web-visitorbadge-nextjs/assets/7326800/9cca1b89-d109-4aaf-9645-57ab141dff92)

Response header | Value
---:|:---
Alt-Svc | `h3=":443"; ma=86400`
Cache-Control | `no-cache, no-store, must-revalidate`
Cf-Cache-Status | `DYNAMIC`
Cf-Ray | `89a845400c217b5f-DME`
Content-Encoding | `br`
Content-Type | `image/svg+xml`
Date | `Thu, 27 Jun 2024 20:43:45 GMT`
Expires | `Thu, 27 Jun 2024 09:42:40 GMT`
Nel | `{"success_fraction":0,"report_to":"cf-nel","max_age":604800}`
Report-To | `{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=..."}],"group":"cf-nel","max_age":604800}`
Request-Context | `appId=cid-v1:0e1d12e3-d444-4b05-a4ec-89eb0328519a`
Server | `cloudflare`
X-Azure-Ref | `20240627T204338Z-16bdf95d48c6h7fz7vcufmy0h0000000030000000000b1dt`
X-Cache | `CONFIG_NOCACHE`

> [!TIP]
> It seems like an issue on your server side...

**Comment by estruyf** [comment]
I have been looking into the issue by testing the API from a VPN, but the maximum load time was always less than 2 seconds.

On the service itself, I have seen some spikes in usage over the last couple of weeks. You might have requested the badge during one of those high spikes.

I configured an availability test that runs on multiple locations to verify the load times. I will let this run for a while to see if I can see some patterns over time. For now, all seems to be fine.

<img width="957" alt="image" src="https://github.com/estruyf/web-visitorbadge-nextjs/assets/2900833/2a2ef541-d668-4034-9a53-632b3d74f90c">

**Comment by tarampampam** [comment]
```
# existing path
$ time curl -Ss -o /dev/null 'https://api.visitorbadge.io/api/visitors?path=test2&label=TEMPLATE_NAME&countColor=%23007ec6'
real	0m0.439s
user	0m0.052s
sys	0m0.000s

# a new one
$ time curl -Ss -o /dev/null 'https://api.visitorbadge.io/api/visitors?path=test123123&label=TEMPLATE_NAME&countColor=%23007ec6'
real	0m6.473s
user	0m0.046s
sys	0m0.007s

# existing
$ time curl -Ss -o /dev/null 'https://api.visitorbadge.io/api/visitors?path=test2&label=TEMPLATE_NAME&countColor=%23007ec6&readonly=true'
real	0m0.523s
user	0m0.041s
sys	0m0.011s

# a new one
$ time curl -Ss -o /dev/null 'https://api.visitorbadge.io/api/visitors?path=test123123123&label=TEMPLATE_NAME&countColor=%23007ec6&readonly=true'
real	0m6.296s
user	0m0.049s
sys	0m0.011s
```

It appears that the issue persists with the "create new" operations. The "increment & read" operations, however, seem to be performing much better!

**Comment by estruyf** [comment]
For new ones, some extra logic gets executed, which might lead to an increase and only happens once 😄. Thanks for testing!

**Comment by estruyf** [comment]
@tarampampam I have made some changes on the backend, and the performance for new badges should now be much better.
