### ISSUE TITLE
What about an initial count value?

### ISSUE THREAD

**Issue by neuralpain** [estruyf/web-visitorbadge-nextjs#13]
Would it be possible to add an initial count value if you already have a value from a different service? I currently use www.websitecounterfree.com for one of my repositories but the styling for your badge is more in line with the culture here on Github, and the ability to add an initial count would be helpful for a switch.

**Comment by estruyf** [comment]
Hi @neuralpain, there is no option for you to set an initial number, I have to do this manually for your record.
