### ISSUE TITLE
need to encode special character & emojis to URL in label

### ISSUE THREAD

**Issue by SaicharanKandukuri** [estruyf/web-visitorbadge-nextjs#3]
Hello @estruyf 

Thanks for making a `non-dev` looking badge generator i found some issues with it

found that your website is not encoding special characters in the label to URL format which lead to crazy boxes & triangles in other sites except the badge generator site

- Without URL encoding ( generated by site )
```html
<p href="https://visitorbadge.io/status?path=https%3A%2F%2Fgithub.com%2FRandomCoderOrg%2Fubuntu-on-android" ><img src="https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Fgithub.com%2FRandomCoderOrg%2Fubuntu-on-android&label=🥳VISITORS&labelColor=%23ffff00&countColor=%23263759" /><p>
```
<p href="https://visitorbadge.io/status?path=https%3A%2F%2Fgithub.com%2FRandomCoderOrg%2Fubuntu-on-android" ><img src="https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Fgithub.com%2FRandomCoderOrg%2Fubuntu-on-android&label=🥳VISITORS&labelColor=%23ffff00&countColor=%23263759" /><p>

- with URL encoding ( after fixing  🥳 → `%F0%9F%A5%B3` )
```html
<p href="https://visitorbadge.io/status?path=https%3A%2F%2Fgithub.com%2FRandomCoderOrg%2Fubuntu-on-android" ><img src="https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Fgithub.com%2FRandomCoderOrg%2Fubuntu-on-android&label=%F0%9F%A5%B3VISITORS&labelColor=%23ffff00&countColor=%23263759" /><p>
```
<p href="https://visitorbadge.io/status?path=https%3A%2F%2Fgithub.com%2FRandomCoderOrg%2Fubuntu-on-android" ><img src="https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Fgithub.com%2FRandomCoderOrg%2Fubuntu-on-android&label=%F0%9F%A5%B3VISITORS&labelColor=%23ffff00&countColor=%23263759" /><p>

looks spaces not encoded to URL that means missing implementation to encode label to URL
![image](https://user-images.githubusercontent.com/68287637/142635962-59de5f9b-7982-4337-b78c-888ec7282fee.png)
![image](https://user-images.githubusercontent.com/68287637/142636014-15152b36-7830-4a08-8e1f-abebb5424940.png)

**Comment by estruyf** [comment]
Thanks @SaicharanKandukuri! I'll get this one fixed

**Comment by estruyf** [comment]
Thanks again @SaicharanKandukuri, the label will now be encoded by default.
