### ISSUE TITLE
Shields.io styling

### ISSUE THREAD

**Issue by jiridj** [estruyf/web-visitorbadge-nextjs#4]
Hi @estruyf, I love this one! 

I noticed the text styles inside the badge do not follow the same styles as badges generated via [shields.io](https://shields.io). For example, via shields.io the flat style has lowercase text and less spacing between the characters. It makes the visitors badge look weird among the other ones, unless you change all other badges to match the visitors badge style.

**Comment by estruyf** [comment]
Thanks, @jiridj will update this to match it! Thanks for opening the issue.

**Comment by estruyf** [comment]
@jiridj I did an update, now only the default style will contain uppercased text, all others are now lowercased.
