### ISSUE TITLE
Counting starts at 2, not 1

### ISSUE THREAD

**Issue by NUROISEA** [estruyf/web-visitorbadge-nextjs#8]
It seems like if any counter is at 0 and being incremented, it skips the count to 2 and after that it counts normally.

I noticed this when I am totaling the week stats including `today` on a newly created key.

Take a look at this status page of [`test/nesting`](https://visitorbadge.io/status?path=test/nesting) or through the [API](https://api.visitorbadge.io/api/status?path=test/nesting)

It's total is 3, today is 2, and yesterday is 2. The total should be 4, not 3 and I only viewed this badge 2 times.

----

I visited the badge one more time (after a couple of days).

Total is 4, today is 2, on 04-29 its 2, and on 04-28 its 2. I have only visited this badge 3 times.

I've also included the JSON response of the API.

<details><summary>JSON data as of 2023-05-03</summary>

```
{
  "total": 4,
  "today": 2,
  "dailyResults": [
    {
      "title": "2023-05-02",
      "total": 0,
      "browsers": null,
      "countries": null
    },
    {
      "title": "2023-05-01",
      "total": 0,
      "browsers": null,
      "countries": null
    },
    {
      "title": "2023-04-30",
      "total": 0,
      "browsers": null,
      "countries": null
    },
    {
      "title": "2023-04-29",
      "total": 2,
      "browsers": {},
      "countries": {}
    },
    {
      "title": "2023-04-28",
      "total": 2,
      "browsers": {},
      "countries": {}
    },
    {
      "title": "2023-04-27",
      "total": 0,
      "browsers": null,
      "countries": null
    },
    {
      "title": "2023-04-26",
      "total": 0,
      "browsers": null,
      "countries": null
    }
  ],
  "pageResults": []
}
```

</details>

**Comment by estruyf** [comment]
Thanks @NUROISEA! This issue just got fixed. Good catch 🙏
